import { notFound } from "next/navigation";
import { getPublicSession } from "@/domains/sessions/queries";
import { generatePlayerRecap } from "@/lib/recap";
import { RecapView } from "@/domains/sessions/components/RecapView";
import { PollForm } from "@/domains/polls/components/PollForm";
import { Separator } from "@/components/ui/separator";
import { formatDate } from "@/lib/utils";

export default async function SharePage({
  params,
}: {
  params: Promise<{ sessionId: string }>;
}) {
  const { sessionId: shareToken } = await params;

  const data = await getPublicSession(shareToken);
  if (!data) notFound();

  const { session, threads, mentions } = data;
  const sessionId = session.id;

  const playerRecap = generatePlayerRecap(session, threads, mentions);

  return (
    <div className="max-w-xl mx-auto p-4 sm:p-8">
      <div className="mb-8 text-center space-y-1">
        <p className="text-xs text-muted-foreground uppercase tracking-wide">
          Player recap
        </p>
        <h1 className="text-xl font-bold">
          {session.title ?? `Session — ${formatDate(session.date)}`}
        </h1>
        <p className="text-sm text-muted-foreground">{formatDate(session.date)}</p>
      </div>
      <RecapView recap={playerRecap} mode="player" />

      <Separator className="my-10" />

      <div className="space-y-4">
        <div className="text-center space-y-1">
          <h2 className="text-lg font-semibold">How was the session?</h2>
          <p className="text-sm text-muted-foreground">Let your DM know what you thought.</p>
        </div>
        <PollForm sessionId={sessionId} campaignId={session.campaign_id} />
      </div>

      <p className="mt-10 text-center text-xs text-muted-foreground">
        Generated by Campaign Keeper
      </p>
    </div>
  );
}
