import { notFound } from "next/navigation";
import { adminDb } from "@/lib/firebase/admin";
import { toSession, toThread } from "@/lib/firebase/converters";
import { SESSIONS_COL, THREADS_COL, NPC_MENTIONS_COL } from "@/lib/firebase/db";
import { generatePlayerRecap } from "@/lib/recap";
import { RecapView } from "@/components/sessions/RecapView";
import { PollForm } from "@/components/polls/PollForm";
import { Separator } from "@/components/ui/separator";
import { formatDate } from "@/lib/utils";
import type { NpcMentionWithNpc, Npc } from "@/types";

export default async function SharePage({
  params,
}: {
  params: Promise<{ sessionId: string }>;
}) {
  const { sessionId: shareToken } = await params;
  const db = adminDb();

  const sessionSnap = await db
    .collection(SESSIONS_COL)
    .where("shareToken", "==", shareToken)
    .limit(1)
    .get();

  if (sessionSnap.empty) notFound();

  const sessionDoc = sessionSnap.docs[0];
  const session = toSession(sessionDoc);
  const sessionId = session.id;

  const [threadsSnap, mentionsSnap] = await Promise.all([
    db.collection(THREADS_COL)
      .where("sessionId", "==", sessionId)
      .where("visibility", "==", "public")
      .get(),
    db.collection(NPC_MENTIONS_COL)
      .where("sessionId", "==", sessionId)
      .where("visibility", "==", "public")
      .get(),
  ]);
  const threads = threadsSnap.docs.map(toThread);

  // Build NpcMentionWithNpc from denormalized data — never use privateNotes
  const mentions: NpcMentionWithNpc[] = mentionsSnap.docs.map((doc) => {
    const d = doc.data();
    const fakeNpc: Npc = {
      id: d.npcId,
      campaign_id: session.campaign_id,
      name: d.npcName,
      disposition: d.npcDisposition ?? null,
      portrait_url: null,
      stats_link: null,
      status: null,
      last_scene: null,
      public_info: null,
      private_notes: null,
      created_at: "",
      updated_at: "",
    };
    return {
      id: doc.id,
      npc_id: d.npcId,
      session_id: sessionId,
      visibility: "public" as const,
      note: d.note ?? null,
      created_at: "",
      npc: fakeNpc,
    };
  });

  const playerRecap = generatePlayerRecap(session, threads, mentions);

  return (
    <div className="max-w-xl mx-auto p-4 sm:p-8">
      <div className="mb-8 text-center space-y-1">
        <p className="text-xs text-muted-foreground uppercase tracking-wide">
          Player recap
        </p>
        <h1 className="text-xl font-bold">
          {session.title ?? `Session — ${formatDate(session.date)}`}
        </h1>
        <p className="text-sm text-muted-foreground">{formatDate(session.date)}</p>
      </div>
      <RecapView recap={playerRecap} mode="player" />

      <Separator className="my-10" />

      <div className="space-y-4">
        <div className="text-center space-y-1">
          <h2 className="text-lg font-semibold">How was the session?</h2>
          <p className="text-sm text-muted-foreground">Let your DM know what you thought.</p>
        </div>
        <PollForm sessionId={sessionId} campaignId={session.campaign_id} />
      </div>

      <p className="mt-10 text-center text-xs text-muted-foreground">
        Generated by Campaign Keeper
      </p>
    </div>
  );
}
